import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR">
      <body>
        {/* --- blob accent ------------------------------------------------- */}
        <div
          aria-hidden
          className="fixed -top-24 -right-24 w-[480px] h-[480px]
                     bg-accent/20 rounded-full blur-[180px] -z-10" />
        {/* --------------------------------------------------------------- */}
        {children}
      </body>
    </html>
  );
}
